# Generated by Django 3.1.5 on 2021-02-15 06:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default=False),
        ),
    ]
