# Generated by Django 3.1.5 on 2021-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('Status', models.BooleanField(default=True)),
                ('Position', models.IntegerField()),
            ],
            options={
                'ordering': ['Position'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='work',
            field=models.BooleanField(verbose_name='نمونه کار'),
        ),
    ]
