# Generated by Django 3.1.5 on 2021-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210129_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.ManyToManyField(related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='نمایش داده شود'),
        ),
    ]
