# Generated by Django 3.1.5 on 2021-02-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
