# Generated by Django 3.1.5 on 2021-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Position',
            field=models.IntegerField(blank=True, default=1, verbose_name='پوزیشن'),
            preserve_default=False,
        ),
    ]
