# Generated by Django 3.1.5 on 2021-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(default='about', unique=True, verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
