# Generated by Django 3.1.5 on 2021-02-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباه ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='Position',
        ),
    ]
