# Generated by Django 3.1.5 on 2021-02-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20201023_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'پرچم', 'verbose_name_plural': 'پرچم ها'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ ها'},
        ),
    ]
